import { atom } from 'recoil';

const todosAtom = atom({
    key: "todosAtom",
    default: [
        { title: "Buy groceries", description: "Pick up fruits, vegetables, and snacks from the supermarket." },
        { title: "Clean the house", description: "Vacuum the living room, dust the shelves, and clean the windows." },
        { title: "Finish project report", description: "Complete the final draft of the project report for work." },
        { title: "Call mom", description: "Catch up with mom over the phone and see how she’s doing." },
        { title: "Buy groceries", description: "Pick up groceries for the week." },
        { title: "Clean house", description: "Vacuum and dust the living room." },
        { title: "Clean house", description: "Mop the kitchen and bathroom floors." },
        { title: "Finish project report", description: "Review and submit the project report." },
        { title: "Finish project report", description: "Send the final report to the team." },
        { title: "Call mom", description: "Call mom for a quick chat." },
        { title: "Read a book", description: "Read 20 pages of the book 'Atomic Habits'." },
        { title: "Read a book", description: "Read 10 pages from 'The Power of Habit'." },
        { title: "Go for a walk", description: "Take a 30-minute walk in the park to get some fresh air." },
        { title: "Go for a walk", description: "Go for a 30-minute walk around the neighborhood." },
        { title: "Pay bills", description: "Pay the electricity, water, and internet bills." },
        { title: "Pay rent", description: "Pay the monthly rent for the apartment." },
        { title: "Email John", description: "Send an email to John about the upcoming meeting." },
        { title: "Email John", description: "Follow up with John on the project status." },
        { title: "Organize closet", description: "Sort through clothes and donate anything not worn in the last year." },
        { title: "Organize closet", description: "Organize shoes and jackets in the closet." },
        { title: "Workout", description: "Do a 45-minute home workout session." },
        { title: "Workout", description: "Complete a 30-minute cardio workout." },
        { title: "Plan vacation", description: "Start researching and planning for a summer vacation destination." },
        { title: "Plan vacation", description: "Look up travel destinations for the winter break." },
        { title: "Check emails", description: "Go through and respond to work and personal emails." },
        { title: "Check emails", description: "Reply to important emails." },
        { title: "Attend online course", description: "Complete 1 module of the online Python course." },
        { title: "Attend online course", description: "Watch the next video in the UX design course." },
        { title: "Clean fridge", description: "Throw away expired items and organize the fridge." },
        { title: "Clean fridge", description: "Clean the fridge shelves and wipe down the surfaces." },
        { title: "Update resume", description: "Make improvements and update current job details in the resume." },
        { title: "Update resume", description: "Add recent projects to the resume." },
        { title: "Prepare lunch", description: "Make a healthy salad for lunch with chicken and avocado." },
        { title: "Prepare lunch", description: "Prepare a quinoa bowl with vegetables for lunch." },
        { title: "Schedule doctor's appointment", description: "Call the clinic and book a check-up appointment." },
        { title: "Schedule dentist appointment", description: "Book a dentist appointment for cleaning." },
        { title: "Take out trash", description: "Take the trash out to the curb for pickup." },
        { title: "Take out trash", description: "Empty the kitchen and bathroom trash cans." },
        { title: "Meditate", description: "Do 10 minutes of meditation to relax and clear my mind." },
        { title: "Meditate", description: "Try a 15-minute guided meditation for stress relief." },
        { title: "Write blog post", description: "Write and publish a new blog post about personal growth." },
        { title: "Write blog post", description: "Write a blog post on self-care tips." },
        { title: "Clean bathroom", description: "Scrub the toilet, sink, and clean the shower." },
        { title: "Clean bathroom", description: "Clean the mirrors and wash the bathroom floor." },
        { title: "Prepare dinner", description: "Make a quick dinner of pasta and marinara sauce." },
        { title: "Prepare dinner", description: "Cook a stir-fry with vegetables and rice for dinner." },
        { title: "Watch a movie", description: "Watch a new release movie for some relaxation." },
        { title: "Watch a movie", description: "Watch a comedy movie on Netflix." },
        { title: "Visit a friend", description: "Meet up with a friend for coffee and catch up." },
        { title: "Visit a friend", description: "Catch up with Sarah over lunch." },
        { title: "Laundry", description: "Wash, dry, fold, and put away laundry." },
        { title: "Laundry", description: "Do a load of laundry and sort clothes." },
        { title: "Water plants", description: "Water all indoor plants to keep them healthy." },
        { title: "Water plants", description: "Check the garden and water the outdoor plants." },
        { title: "Check bank account", description: "Review recent transactions and check account balance." },
        { title: "Check bank account", description: "Look over the recent spending and savings report." },
        { title: "Take vitamins", description: "Take daily vitamins for overall health." },
        { title: "Take vitamins", description: "Remember to take the multivitamins and fish oil." },
        { title: "Organize desk", description: "Tidy up the desk and throw away any clutter." },
        { title: "Organize desk", description: "Sort through the papers and clear the workspace." },
        { title: "Walk dog", description: "Take the dog for a 30-minute walk in the neighborhood." },
        { title: "Walk dog", description: "Take the dog to the park for a walk." },
        { title: "Buy new shoes", description: "Purchase a new pair of comfortable shoes for walking." },
        { title: "Buy new shoes", description: "Order running shoes online." },
        { title: "Meet with team", description: "Hold a team meeting to discuss project updates." },
        { title: "Meet with team", description: "Set up a meeting with the team to brainstorm ideas." },
        { title: "Book flight", description: "Book a flight for the upcoming business trip." },
        { title: "Book flight", description: "Reserve a flight for the holiday trip." },
        { title: "Write thank you notes", description: "Write and send thank you notes for recent gifts." },
        { title: "Write thank you notes", description: "Send thank you notes to family for the birthday gifts." },
        { title: "Call customer service", description: "Call customer service to resolve an issue with an order." },
        { title: "Call customer service", description: "Resolve billing issues with the service provider." },
        { title: "Finish book", description: "Finish reading 'The Subtle Art of Not Giving a F*ck'." },
        { title: "Finish book", description: "Complete the last chapters of 'Educated' by Tara Westover." },
        { title: "Check weather", description: "Check the weather forecast for the upcoming week." },
        { title: "Check weather", description: "Look up the weather for the weekend trip." },
        { title: "Schedule meeting", description: "Schedule a meeting with the marketing team." },
        { title: "Schedule meeting", description: "Arrange a one-on-one meeting with my manager." },
        { title: "Submit application", description: "Submit job application for the marketing position." },
        { title: "Submit application", description: "Apply for the product manager role." },
        { title: "Take a nap", description: "Take a 20-minute power nap to refresh." },
        { title: "Take a nap", description: "Relax and take a short afternoon nap." },
        { title: "Fix the sink", description: "Fix the leaky sink in the kitchen." },
        { title: "Fix the sink", description: "Repair the clogged drain in the bathroom." },
        { title: "Donate clothes", description: "Donate gently used clothes to a local charity." },
        { title: "Donate clothes", description: "Clear out the closet and donate to charity." },
        { title: "Prepare for presentation", description: "Finish slides and practice presentation for work." },
        { title: "Prepare for presentation", description: "Practice my presentation for the upcoming conference." },
        { title: "Clean windows", description: "Clean all windows inside and outside for a clear view." },
        { title: "Clean windows", description: "Wash the windows in the living room and bedroom." },
        { title: "Finish puzzle", description: "Complete the 1000-piece jigsaw puzzle on the coffee table." },
        { title: "Finish puzzle", description: "Finish assembling the puzzle by the fireplace." },
        { title: "Go to the gym", description: "Attend a 1-hour gym session for a strength workout." },
        { title: "Go to the gym", description: "Do a 45-minute workout session at the gym." },
        { title: "Buy new books", description: "Purchase a few new books to read next month." },
        { title: "Buy new books", description: "Order new books from the online bookstore." },
        { title: "Check calendar", description: "Review the calendar for upcoming appointments and events." },
        { title: "Check calendar", description: "Look through the calendar for next week's schedule." }
    ]
});

export default todosAtom; 